#!/bin/bash

. cleanup.sh

export LD_LIBRARY_PATH=${_PYPKG_ENV_BACKUP_LD_LIBRARY_PATH}
export PKG_CONFIG_PATH=${_PYPKG_ENV_BACKUP_PKG_CONFIG_PATH}
export PKG_CONFIG_LIBDIR=${_PYPKG_ENV_BACKUP_PKG_CONFIG_LIBDIR}

deactivate

